# Exclude files/directories from linting
exclude = [
    ".git",
    ".venv",
    "__pycache__",
    "build",
    "dist",
]

# Enable all rules by default
lint.select = ["ALL"]

# Ignore specific rules
lint.ignore = [
    "D203",  # no-blank-line-before-class
    "D212",  # multi-line-summary-first-line
    "COM812",
    "D100",
    "UP017"
]

# Line length to match black default
line-length = 160

# Assume Python 3.13
target-version = "py313"

[lint.per-file-ignores]
"tests/*" = [
    "S101",   # assert statements in tests are fine
    "ARG",    # unused arguments in tests are fine
    "PLR2004" # magic numbers in tests are fine
]

[lint.mccabe]
max-complexity = 10

[lint.flake8-quotes]
docstring-quotes = "double"
inline-quotes = "double"

[lint.pydocstyle]
convention = "google"

[lint.isort]
combine-as-imports = true
known-first-party = ["app"]